theme: minima
title: Long Answer
author: Amina Khattak
description: This blog was born out of necessity. In my various workplace and networking sessions, I get asked or prompted about situations relating to Learning and Development, Customer Education, organizational dynamics, people management, and more. I find myself increasingly giving long answers to short questions. Hence the origin of this blog.
